alias rs='rsync -chavzP --stats'
alias ll='ls -l'
alias la='ls -lAFh'
alias ls='ls --color=tty'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias gd='git diff'
alias gdca='git diff --cached'
alias gss='git status -s'
alias gs='git status'
alias gco='git checkout'
alias gl='git pull'
alias gcmsg='git commit -m'
alias h='history'

PS1='\[\e[0;32m\]\u@\h\[\e[m\] \[\e[1;34m\]\w\[\e[m\] \[\e[1;32m\]\$\[\e[m\] \[\e[1;37m\]'
